version: '3'
services:
  ddns_client:
    build: .
    container_name: ddns_client
    tty: true
    #env_file:
    #  - config.env
    volumes:
      - ./:/home/
      - /home/node_modules/
    networks:
      - br_ipv6_network
    restart: always

networks:
  br_ipv6_network:
    # docker-compose.yml で管理しない外部のネットワークを利用する, ref: https://docs.docker.jp/compose/compose-file/index.html#external
    external: true