version: '3'
services:
  ddns_client:
    build: .
    container_name: ddns_client
    tty: true
    #env_file:
    #  - config.env
    volumes:
      - ./:/home/
      - /home/node_modules/
    restart: always